
server:
  port: ${PORT:8081}

spring:
  application:
    name: customer
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true

    
management:
  endpoints:
    web:
      exposure:
        include: health,metrics